### ISSUE TITLE
Make fluentflow rule asynchronous

### ISSUE THREAD

**Issue by Enteee** [t-moe/FluentFlow#6]
For asynchronous operations inside a rule I'd like to have a callback (instead of a return) which tells the matcher if a rule matched or not.

**Comment by t-moe** [comment]
Ok. Basic async support is implemented.
If a matcher function returns nothing (=`undefined`) the matcher core will wait till the matcher function calls `this.next(...)` with a boolean argument.

**Comment by t-moe** [comment]
Example which shows the technique (but makes totally no sense ):
```
$.match(function(currentObject) {
	var cb = this.next;
	setTimeout(function() {
		cb(currentObject.type == "ForkEvent");
	},100);
}).then(function(){
	console.log("Hey, I had to wait 100ms!");  
});
```

**Comment by Enteee** [comment]
Why are you using this.next instead of an optional function argument?

**Comment by t-moe** [comment]
The number of arguments to the matcher function depends on the position in the chain.
E.g. A matcher function, after 2 "followedBy's" can take up to 3 args. Making the callback an optional last function parameter, would force me to drop the "detect if the function needs the previous objects or not"-support. Making the callback the first function parameter is also bad, for functions that don't use it.
